require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
  SuggestExtensions: false

# Disable Documentation rule for classes
Style/Documentation:
  Enabled: false

# Additional settings to ignore specific warnings
Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/devise.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
