FROM ruby:3.3.2-alpine

ARG WORKDIR=/app  # デフォルト値を/appに設定

ARG RUNTIME_PACKAGES="nodejs tzdata postgresql-dev postgresql git libxml2-dev libxslt-dev libc6-compat vim"  # vimを追加
ARG DEV_PACKAGES="build-base curl-dev g++ make"

ENV HOME=${WORKDIR} \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo

WORKDIR ${WORKDIR}

COPY Gemfile* ./

RUN apk update && \
    apk upgrade && \
    apk add --no-cache ${RUNTIME_PACKAGES} && \
    apk add --virtual build-dependencies --no-cache ${DEV_PACKAGES} && \
    bundle config build.nokogiri --use-system-libraries && \
    bundle install -j4 && \
    apk del build-dependencies

COPY . ./
