default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db
  port: 5432

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: demochat_api_test

production:
  <<: *default
  database: demochat_api_production
  username: demochat
  password: <%= ENV['DEMOMAP_DATABASE_PASSWORD'] %>
