default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: password: <%= ENV["POSTGRES_USER"] %>
  password: password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: demochat_api_test

production:
  <<: *default
  host: demochat-db.internal
  database: demochat_api_production
