default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: demochat_api_test

production:
  <<: *default
  host: demochat-db.internal
  database: demochat_api_production
