default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  # database: app_development

development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: demochat_api_test

production:
  <<: *default
  host: demochat-db.internal
  database: demochat_api_production
