default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: app_development
  host: db

test:
  <<: *default
  database: demochat_api_test

production:
  <<: *default
  host: demochat-db.internal
  database: demochat_api_production
